### ISSUE TITLE
Samples Issue

### ISSUE THREAD

**Issue by Humanoid-X** [pattlebass/Music-DJ#1]
In the samples of piano, reggae and techno samples are sometimes inverted and sometimes even replace each other. Sometimes, I don't even think that this is the music of techno.
I hope this can get fixed as soon as possible.

**Comment by Humanoid-X** [comment]
Ah, not only reggae and techno, all the samples in the piano category is a mess.

**Comment by pattlebass** [comment]
I'll look into it.
Maybe I'll get to fix it by the end of the week. Thanks for pointing it out.

**Comment by pattlebass** [comment]
Fixed in v1.1.1-beta.
