### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by hucenxz** [pattlebass/Music-DJ#15]
### Describe the problem you're having

please add unlimited input fields.  currently it has only 15 columns 

### Describe the solution you'd like

unlimited  row suggestion

**Comment by pattlebass** [comment]
Hi! To add more columns, simply press the + button that is all the way to the right. It will add a new column. 
![image](https://user-images.githubusercontent.com/49322676/226601962-00db3400-dc44-4647-bf0d-dfd329add8e5.png)

If you don't see it let me know
