### ISSUE TITLE
[Feature]: Polish localization and column menu update 

### ISSUE THREAD

**Issue by dawidsadowski** [pattlebass/Music-DJ#16]
### Describe the problem you're having

Hello. 
I don't like that there is only one option for playing the song using the "Play" button in the column menu. Instead I would like to separate this option into two buttons:
1. "Play" - plays a song starting from the selected column until the end of the song.
2. "Play column" - plays a single column (like the "Play" button before). 

### Describe the solution you'd like

I would like to create a pull request with my changes regarding adding few changes I made in the column menu and a new language (Polish).

The changes I made:
1. Added a new localization (Polish),
2. Added new text entries (`BTN_PLAY_COLUMN`, `BTN_COPY`, `BTN_PASTE`),
3. Slightly changed the column menu (now it's vertical),
4. Changed functionality of the "Play" button in the column menu (now it plays a song from the column and continues until the end of the song),
5. Added a new button in the column menu ("Play column" - which is basically the previous "Play" button),
6. Added minor fixes (changed the "Copy" and "Paste" labels to the ones that were mentioned in the 2nd point, so now they are translatable).

### Column menu changes
![image](https://github.com/pattlebass/Music-DJ/assets/72928091/ad9966b7-3a00-4ab0-827c-befedf197224)

### Tile menu fixes
![image](https://github.com/pattlebass/Music-DJ/assets/72928091/fe6ddd08-d0cc-4029-9d03-01118977927b)

### New language
![image](https://github.com/pattlebass/Music-DJ/assets/72928091/b0c4790d-81b5-4a30-85f8-a89f1607652a)

**Comment by pattlebass** [comment]
Closed by #19 and #20
