### ISSUE TITLE
[Bug]: Font does not render

### ISSUE THREAD

**Issue by cabbage-roll** [pattlebass/Music-DJ#18]
### What happened?

On Linux (and Windows exe running through Wine) the font does not render for me.
I don't see any errors in the console, this is the console output. Please help!

```
Godot Engine v3.5.1.stable.official.6fed1ffa3 - https://godotengine.org
OpenGL ES 2.0 Renderer: AMD Radeon(TM) HD8800 Series (pitcairn, LLVM 15.0.3, DRM 3.49, 5.15.0-78-generic)
 
Loaded options.json
```

### Version

v1.5-beta, v1.4.1-beta

### OS/Browser version

Kubuntu 22.04 LTS

### Screenshots / Videos

![image](https://github.com/pattlebass/Music-DJ/assets/62716710/8c89825c-b109-4561-aac1-a8702bd6c9bc)

**Comment by pattlebass** [comment]
Hey! Thanks for reporting the issue!

Unfortunately, I can't reproduce it on my machine. Could you please go through the releases and see what is the newest version of MusicDJ that works?

**Comment by cabbage-roll** [comment]
None of the versions work, the only thing I can think of is that I am missing the font somehow.
