### ISSUE TITLE
TROJAN?!

### ISSUE THREAD

**Issue by Humanoid-X** [pattlebass/Music-DJ#2]
I just finished extracting the file.

When I opened the MusicDJ.exe the computer show![gah](https://user-images.githubusercontent.com/60562028/102156720-19f09080-3eb9-11eb-988a-2875bc887727.png)

And I opened the antivirus. Here's what it show
![huh](https://user-images.githubusercontent.com/60562028/102156762-2ffe5100-3eb9-11eb-8a4e-4301be4bb3b4.png)

I don't know if this can be fixed, but thanks anyway.

**Comment by pattlebass** [comment]
Hi! Can you try v1.1.2-beta? It might have fixed it.

**Comment by Humanoid-X** [comment]
Alright. I will try it. Thanks!

**Comment by Humanoid-X** [comment]
Good, fixed. Thanks!
