### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hamdansss2222** [pattlebass/Music-DJ#22]
### What happened?

Cant play full  music just 1-18 bar

### Version

v1.5-beta

### OS/Browser version

Microsoft Edge

### Device information (phone model or PC specs)

windows 10

### Screenshots / Videos

![image](https://github.com/pattlebass/Music-DJ/assets/141936330/2bf5d7dd-256b-4f4f-bcaf-ed0380f72672)

**Comment by pattlebass** [comment]
Duplicate of #23
