### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by woltaj1453** [pattlebass/Music-DJ#24]
### Describe the problem you're having

![change  mdj](https://github.com/pattlebass/Music-DJ/assets/155825493/58031fa0-2cc1-4083-9105-a424288223d8)

### Describe the solution you'd like

so good

### Screenshots

![image](https://github.com/pattlebass/Music-DJ/assets/155825493/ba0bb7e0-d196-4b05-838c-e27e19506c2a)

**Comment by pattlebass** [comment]
Closing as there is no suggestion here. Please open a new issue and provide more details. Thanks!
