### ISSUE TITLE
[BUG] only hear broken noise on Android Chrome

### ISSUE THREAD

**Issue by kuanyui** [pattlebass/Music-DJ#3]
**Describe the bug**
Can only hear broken noise on Android Chrome.

**To Reproduce**
Open with Chrome 90 + Android 11.

**Expected behavior**
Play sound.

**Screenshots**
https://youtu.be/-hFsPFK66WY

**Context (please complete the following information):**
 - OS: Android 11
 - Version HTML 5

**Additional context**

**Comment by kuanyui** [comment]
I found in Firefox for Android 90, it works normal without this issue.

**Comment by pattlebass** [comment]
Thanks for letting me know! I'll look into it

**Comment by pattlebass** [comment]
Sorry for taking so long.
I made some changes and now it seems to be working fine (Chrome 92, Android 11). Can you please test it again?
@kuanyui

**Comment by kuanyui** [comment]
It works now!

2021年7月31日(土) 3:11 pattlebass ***@***.***>:
