### ISSUE TITLE
[Feature]: Import original MusicDJ MIDI files

### ISSUE THREAD

**Issue by StepS-** [pattlebass/Music-DJ#4]
### Describe the problem you're having

I've got a bunch of MusicDJ MIDI files made on SE K750i back in 2006, ~~however nothing can open or convert them~~. **Edit:** VLC with fluidsynth can in fact open them (thanks to some people for the tips). MusicDJ data appears to be stored in the SEM1 chunk as noted in losnoco/foo_midi#1 and confuses most MIDI decoders.

[MusicDJ_files.zip](https://github.com/pattlebass/Music-DJ/files/7212552/MusicDJ_files.zip)

### Describe the solution you'd like

I was wondering if it would eventually be possible to import the files as projects in this new MusicDJ recreation. However, since I imagine this use case is super rare I'm just leaving it as a "nice to have" in the hopes someone would be compelled enough to work on this.

Thank you!

**Comment by pattlebass** [comment]
@StepS- Good news! `v1.5-beta` just added this.
