### ISSUE TITLE
[Feature]: Export Import from/With Json File

### ISSUE THREAD

**Issue by alfianrehanusa** [pattlebass/Music-DJ#5]
### Describe the problem you're having

i feel from build the song is time consuming. i like try to repetitive bass with 3, 4, 3, 4 without adding manual, like copy paste.

### Describe the solution you'd like

like the title, so we can create song from json format. i can build song only copy paste if i need repetitive song. Reason using json is because much simpler. Any format is good too (txt, xml, etc).

Sorry for my bad english, i hope you understand

**Comment by pattlebass** [comment]
Done! In the next release you'll be able to open `.mdj` project files with any text editor.

**Comment by pattlebass** [comment]
I also added a [tutorial](https://github.com/pattlebass/Music-DJ/wiki/Modify-projects-with-a-text-editor).

**Comment by alfianrehanusa** [comment]
nice, much appreciated
