### ISSUE TITLE
[Feature]: Indonesia localization

### ISSUE THREAD

**Issue by StarryWindy** [pattlebass/Music-DJ#6]
### Describe the problem you're having

I've been using your recreation of MusicDJ because I used to play one or two when I borrowed my family relatives' Sony Ericsson phones back then, and when I saw that you're preparing to do some localization thing, I began to think that Indonesia language should be there, too.

### Describe the solution you'd like

I may have no expertise at coding atm (not my forte yet), but I can do some Indonesian language translation for you. Please do note that I don't have Sony Ericsson phones yet at the time I'm writing this, so some of the translations might possibly be different than what's seen on the phone, and the melody tidbits like Groove, Salsa and all that Jazz (pun intended 😛) are not included. However, you can give me the pointers and previews on how the texts will appear and on which conditions, and I'll do my best to translate for you. I might want to make a pull request when I feel that my translations are fully ready, too.

Thanks in advance 🙂

**Comment by pattlebass** [comment]
Hi! [Here's the spreadsheet I use](https://docs.google.com/spreadsheets/d/1VEE4aROwNFXsZTRbMOShlv2E8XcYVBYYEVsRbFYKBog/edit?usp=drivesdk)

> Speaking of which, I do have one question... I'm wondering, is DIALOG_CONFIRMATION_TITLE_OVERWRITE related to overwriting the project, or is it about overwriting exported songs? Or both?

ATM it refers to overwriting the project but I plan to use it in the future for exported songs too.
